from pathlib import Path

import pytest

from kitshn.caddy import apply_caddyfile, render_caddy_manifest, render_caddyfile
from kitshn.models import Deployment, Recipe, Roots
from kitshn.runner import CommandRunner


def test_caddy_render_receives_full_params_file(tmp_path: Path) -> None:
    deployment = _deployment(tmp_path)
    deployment.deployment_root.mkdir(parents=True)
    deployment.params_root.mkdir(parents=True)
    deployment.params_file.write_text('DOMAIN="example.com"\nTOKEN="secret"\n', encoding="utf-8")
    (deployment.deployment_root / "Caddyfile.j2").write_text(
        "{{ params.DOMAIN }} {\n    header X-Token {{ params.TOKEN }}\n}\n",
        encoding="utf-8",
    )

    assert render_caddyfile(deployment) == "example.com {\n    header X-Token secret\n}\n"


def test_caddy_render_ignores_generated_caddyfile_artifact(tmp_path: Path) -> None:
    deployment = _deployment(tmp_path)
    deployment.deployment_root.mkdir(parents=True)
    deployment.params_root.mkdir(parents=True)
    deployment.params_file.write_text("", encoding="utf-8")
    (deployment.deployment_root / "Caddyfile").write_text("example.com\n", encoding="utf-8")

    assert render_caddyfile(deployment) is None


def test_apply_caddyfile_updates_generated_manifest(tmp_path: Path) -> None:
    deployment = _deployment(tmp_path)

    changed = apply_caddyfile(deployment, "example.com {\n}\n", CommandRunner(dry_run=True))

    assert changed is True
    assert deployment.generated_caddyfile.read_text(encoding="utf-8") == "example.com {\n}\n"
    assert deployment.caddy_manifest_file.read_text(encoding="utf-8") == (
        "# Generated by KitSHn. Do not edit.\n"
        "import owner/repo/prod/Caddyfile\n"
    )


def test_render_caddy_manifest_imports_all_generated_caddyfiles(tmp_path: Path) -> None:
    deployment = _deployment(tmp_path)
    other_deployment = Deployment.create(Recipe.parse("owner/api"), "staging", deployment.roots)
    deployment.generated_caddyfile.parent.mkdir(parents=True)
    other_deployment.generated_caddyfile.parent.mkdir(parents=True)
    deployment.generated_caddyfile.write_text("example.com {\n}\n", encoding="utf-8")
    other_deployment.generated_caddyfile.write_text("api.example.com {\n}\n", encoding="utf-8")

    assert render_caddy_manifest(deployment.roots) == (
        "# Generated by KitSHn. Do not edit.\n"
        "import owner/api/staging/Caddyfile\n"
        "import owner/repo/prod/Caddyfile\n"
    )


def test_apply_caddyfile_restores_manifest_when_validation_fails(tmp_path: Path) -> None:
    deployment = _deployment(tmp_path)
    deployment.generated_caddyfile.parent.mkdir(parents=True)
    deployment.caddy_manifest_file.parent.mkdir(parents=True, exist_ok=True)
    deployment.generated_caddyfile.write_text("old\n", encoding="utf-8")
    deployment.caddy_manifest_file.write_text("old manifest\n", encoding="utf-8")

    with pytest.raises(RuntimeError):
        apply_caddyfile(deployment, "new\n", FailingRunner(), previous_active="old\n")

    assert deployment.generated_caddyfile.read_text(encoding="utf-8") == "old\n"
    assert deployment.caddy_manifest_file.read_text(encoding="utf-8") == "old manifest\n"


class FailingRunner(CommandRunner):
    def run(self, *args, **kwargs):
        raise RuntimeError("caddy validation failed")


def _deployment(tmp_path: Path) -> Deployment:
    roots = Roots(
        deployments=tmp_path / "deployments",
        params=tmp_path / "params",
        persistent=tmp_path / "persistent",
        logs=tmp_path / "logs",
    )
    return Deployment.create(Recipe.parse("owner/repo"), "prod", roots)
