from pathlib import Path
import os
import stat

import pytest

import kitshn.caddy
from kitshn.caddy import (
    apply_caddyfile,
    caddy_dns_zones,
    caddy_validate_command,
    infer_public_url,
    render_caddy_manifest,
    render_caddyfile,
    site_addresses,
)
from kitshn.errors import KitshnError
from kitshn.models import Deployment, Recipe, Roots
from kitshn.runner import CommandResult, CommandRunner


def test_caddy_render_receives_full_params_file(tmp_path: Path) -> None:
    deployment = _deployment(tmp_path)
    deployment.deployment_root.mkdir(parents=True)
    deployment.params_root.mkdir(parents=True)
    deployment.params_file.write_text('HOST="example.com"\nTOKEN="secret"\n', encoding="utf-8")
    (deployment.deployment_root / "Caddyfile.j2").write_text(
        "{{ params.HOST }} {\n    header X-Token {{ params.TOKEN }}\n}\n",
        encoding="utf-8",
    )

    assert render_caddyfile(deployment) == "example.com {\n    header X-Token secret\n}\n"


def test_caddy_render_ignores_generated_caddyfile_artifact(tmp_path: Path) -> None:
    deployment = _deployment(tmp_path)
    deployment.deployment_root.mkdir(parents=True)
    deployment.params_root.mkdir(parents=True)
    deployment.params_file.write_text("", encoding="utf-8")
    (deployment.deployment_root / "Caddyfile").write_text("example.com\n", encoding="utf-8")

    assert render_caddyfile(deployment) is None


def test_apply_caddyfile_updates_generated_manifest(tmp_path: Path) -> None:
    deployment = _deployment(tmp_path)

    changed = apply_caddyfile(deployment, "example.com {\n}\n", CommandRunner(dry_run=True))

    assert changed is True
    assert deployment.generated_caddyfile.read_text(encoding="utf-8") == "example.com {\n}\n"
    assert deployment.caddy_manifest_file.read_text(encoding="utf-8") == (
        "# Generated by KitSHn. Do not edit.\n"
        "import owner/repo/prod/Caddyfile\n"
    )


def test_render_caddy_manifest_imports_all_generated_caddyfiles(tmp_path: Path) -> None:
    deployment = _deployment(tmp_path)
    other_deployment = Deployment.create(Recipe.parse("owner/api"), "staging", deployment.roots)
    deployment.generated_caddyfile.parent.mkdir(parents=True)
    other_deployment.generated_caddyfile.parent.mkdir(parents=True)
    deployment.generated_caddyfile.write_text("example.com {\n}\n", encoding="utf-8")
    other_deployment.generated_caddyfile.write_text("api.example.com {\n}\n", encoding="utf-8")

    assert render_caddy_manifest(deployment.roots) == (
        "# Generated by KitSHn. Do not edit.\n"
        "import owner/api/staging/Caddyfile\n"
        "import owner/repo/prod/Caddyfile\n"
    )


def test_apply_caddyfile_restores_manifest_when_validation_fails(tmp_path: Path) -> None:
    deployment = _deployment(tmp_path)
    deployment.generated_caddyfile.parent.mkdir(parents=True)
    deployment.caddy_manifest_file.parent.mkdir(parents=True, exist_ok=True)
    deployment.generated_caddyfile.write_text("old\n", encoding="utf-8")
    deployment.caddy_manifest_file.write_text("old manifest\n", encoding="utf-8")

    with pytest.raises(RuntimeError):
        apply_caddyfile(deployment, "new\n", FailingRunner(), previous_active="old\n")

    assert deployment.generated_caddyfile.read_text(encoding="utf-8") == "old\n"
    assert deployment.caddy_manifest_file.read_text(encoding="utf-8") == "old manifest\n"


def test_apply_caddyfile_hints_for_ambiguous_sites(tmp_path: Path) -> None:
    deployment = _deployment(tmp_path)

    with pytest.raises(KitshnError, match="environment-aware"):
        apply_caddyfile(deployment, "example.com {\n}\n", AmbiguousSiteRunner())


class FailingRunner(CommandRunner):
    def run(self, *args, **kwargs):
        raise RuntimeError("caddy validation failed")


class AmbiguousSiteRunner(CommandRunner):
    def run(self, args, **kwargs):
        command = list(args)
        if command[:2] == ["caddy", "validate"]:
            return CommandResult(
                args=args,
                returncode=1,
                stdout="",
                stderr="Error: adapting config using caddyfile: ambiguous site definition: example.com",
            )
        return CommandResult(args=args, returncode=0, stdout="", stderr="")


def _deployment(tmp_path: Path) -> Deployment:
    roots = Roots(
        deployments=tmp_path / "deployments",
        params=tmp_path / "params",
        persistent=tmp_path / "persistent",
        logs=tmp_path / "logs",
    )
    return Deployment.create(Recipe.parse("owner/repo"), "prod", roots)


def test_site_addresses_skip_global_options_snippets_and_nested_blocks() -> None:
    caddyfile = """{
    email admin@example.com
}
(shared) {
    encode gzip
}
# comment
example.com, www.example.com {
    reverse_proxy unix//sock {
        header_up Host {host}
    }
}
http://internal.example.com:8080 {
}
"""
    assert site_addresses(caddyfile) == ["example.com", "www.example.com", "http://internal.example.com:8080"]


@pytest.mark.parametrize(
    ("template", "environment", "expected"),
    [
        ('{{ host("site.example.com") }} {\n    reverse_proxy unix//{{ paths.default_socket }}\n}\n', "prod", "https://site.example.com"),
        ('{{ host("site.example.com") }} {\n    reverse_proxy unix//{{ paths.default_socket }}\n}\n', "pr-7", "https://pr-7.site.example.com"),
        ("http://plain.example.com {\n}\n", "prod", "http://plain.example.com"),
        ("http://internal.example.com:8080 {\n}\n", "prod", "http://internal.example.com:8080"),
        ("*.example.com {\n}\n", "prod", None),
        ("a.example.com {\n}\nb.example.com {\n}\n", "prod", None),
        (":443 {\n    reverse_proxy unix//{{ paths.default_socket }}\n}\n", "prod", None),
        ("dozzle.example.com {\n    basic_auth {\n        {{ params.USER }} {{ params.HASH }}\n    }\n}\n", "prod", "https://dozzle.example.com"),
    ],
)
def test_infer_public_url_only_returns_a_single_concrete_host(tmp_path: Path, template: str, environment: str, expected: str | None) -> None:
    deployment = Deployment.create(Recipe.parse("owner/repo"), environment, _deployment(tmp_path).roots)
    template_path = tmp_path / "Caddyfile.j2"
    template_path.write_text(template, encoding="utf-8")

    assert infer_public_url(template_path, deployment) == expected
    assert infer_public_url(tmp_path / "missing.j2", deployment) is None


def test_host_names_prod_by_its_base_and_other_environments_one_label_below(tmp_path: Path) -> None:
    prod = _rendered(tmp_path, "prod", '{{ host("app.example.com") }} {\n}\n')
    preview = _rendered(tmp_path, "pr-7", '{{ host("app.example.com") }} {\n}\n')

    assert prod == "app.example.com {\n}\n"
    assert preview.splitlines()[-2:] == ["pr-7.app.example.com {", "}"]
    assert site_addresses(preview) == ["pr-7.app.example.com"]


@pytest.mark.parametrize("base", ["", "*.app.example.com", "localhost"])
def test_host_rejects_a_base_that_is_not_a_domain_name(tmp_path: Path, base: str) -> None:
    with pytest.raises(KitshnError, match="host"):
        _rendered(tmp_path, "pr-7", f'{{{{ host("{base}") }}}} {{\n}}\n')


def test_manifest_adds_one_wildcard_site_per_preview_base_when_dns_is_set_up(tmp_path: Path) -> None:
    roots = _deployment(tmp_path).roots
    for environment in ("prod", "pr-7", "pr-8"):
        deployment = Deployment.create(Recipe.parse("owner/repo"), environment, roots)
        rendered = _rendered(tmp_path, environment, '{{ host("app.example.com") }} {\n}\n')
        deployment.generated_caddyfile.parent.mkdir(parents=True, exist_ok=True)
        deployment.generated_caddyfile.write_text(rendered, encoding="utf-8")

    manifest = render_caddy_manifest(roots, dns_zones=frozenset({"example.com"}))

    assert manifest.count("*.app.example.com {") == 1
    assert "\ttls {\n\t\tdns\n\t}\n\tabort\n" in manifest
    assert "import owner/repo/pr-8/Caddyfile" in manifest
    assert "*." not in render_caddy_manifest(roots, dns_zones=frozenset())
    assert "*." not in render_caddy_manifest(roots, dns_zones=frozenset({"other.com"}))


def test_dns_zones_come_from_the_options_file_only_with_a_dns_provider(tmp_path: Path) -> None:
    options = tmp_path / "options.caddy"
    assert caddy_dns_zones(options) == frozenset()
    options.write_text("# kitshn dns zone: example.com\n", encoding="utf-8")
    assert caddy_dns_zones(options) == frozenset()
    options.write_text("# kitshn dns zone: example.com\ndns cloudflare {env.TOKEN}\n", encoding="utf-8")
    assert caddy_dns_zones(options) == frozenset({"example.com"})


def test_validation_loads_the_caddy_environment_file(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    env_file = tmp_path / "kitshn.env"
    monkeypatch.setattr(kitshn.caddy, "CADDY_ENV_FILE", env_file)
    runner = CommandRunner(dry_run=True)
    assert "--envfile" not in caddy_validate_command(runner)

    env_file.write_text("TOKEN=x\n", encoding="utf-8")

    assert caddy_validate_command(runner)[-2:] == ["--envfile", str(env_file)]


@pytest.mark.skipif(os.geteuid() != 0, reason="only root can chown the route to root")
def test_generated_caddyfile_is_readable_only_by_root_and_the_caddy_group(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    monkeypatch.setattr(kitshn.caddy, "caddy_group", lambda _runner: os.getgid())
    deployment = _deployment(tmp_path)

    apply_caddyfile(deployment, "example.com {\n}\n", CommandRunner(dry_run=True))

    assert stat.S_IMODE(deployment.generated_caddyfile.stat().st_mode) == 0o640


def _rendered(tmp_path: Path, environment: str, template: str) -> str:
    deployment = Deployment.create(Recipe.parse("owner/repo"), environment, _deployment(tmp_path).roots)
    deployment.deployment_root.mkdir(parents=True, exist_ok=True)
    (deployment.deployment_root / "Caddyfile.j2").write_text(template, encoding="utf-8")
    rendered = render_caddyfile(deployment)
    assert rendered is not None
    return rendered
