on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, closed]
  workflow_dispatch:
    inputs:
      environment: { required: true, type: string }
      ref: { required: false, type: string }

jobs:
  call:
    uses: kitshn-org/kitshn/.github/workflows/deploy.yml@v1
    secrets: inherit
