"""Host-level Caddy setup that bootstrap owns: the binary, global options, and service environment.

All of it is opt-in. A wildcard preview certificate needs all three: a Caddy build with a DNS
provider module, a global `dns` option, and the provider's API token in Caddy's environment.
"""

from __future__ import annotations

from collections.abc import Callable
from contextlib import AbstractContextManager, nullcontext
from dataclasses import dataclass, field
from pathlib import Path
import os
import stat
import sys
import tempfile
from typing import Literal

from .caddy import (
    CADDY_BASE_CONFIG,
    CADDY_ENV_FILE,
    CADDY_OPTIONS_FILE,
    DNS_ZONE_MARKER,
    caddy_dns_zones,
    caddy_group,
    caddy_validate_command,
    redact_caddy_env,
)
from .errors import KitshnError
from .filesystem import read_env_file
from .runner import CommandRunner

CADDY_BINARY = Path("/usr/bin/caddy")
# A dpkg diversion moves the packaged binary here, so a package upgrade never overwrites the
# custom build. Caddy's install docs describe the same diversion for custom builds.
PACKAGED_BINARY = Path("/usr/bin/caddy.default")
PREVIOUS_BINARY = Path("/usr/bin/caddy.kitshn-previous")
SYSTEMD_DROP_IN = Path("/etc/systemd/system/caddy.service.d/kitshn.conf")
ZEROSSL_ACME_DIRECTORY = "https://acme.zerossl.com/v2/DV90"
GENERATED_HEADER = "# Generated by KitSHn. Do not edit."


@dataclass(frozen=True, slots=True)
class CaddyModule:
    """A Go module path with a pinned version, for example github.com/caddy-dns/cloudflare@v0.2.4."""

    path: str
    version: str

    @classmethod
    def parse(cls, spec: str) -> CaddyModule:
        path, separator, version = spec.strip().partition("@")
        if not separator or not path or not version.startswith("v") or _has_whitespace(spec.strip()):
            msg = f"Caddy module must pin a version as <module path>@v<version>: {spec!r}"
            raise KitshnError(msg)
        return cls(path, version)

    def __str__(self) -> str:
        return f"{self.path}@{self.version}"


@dataclass(frozen=True, slots=True)
class CaddyHostSettings:
    modules: list[CaddyModule] = field(default_factory=list)
    # Sets the global ACME email and adds ZeroSSL as the fallback issuer after Let's Encrypt.
    acme_email: str | None = None
    # The global `dns` option, for example "cloudflare {env.CLOUDFLARE_API_TOKEN}".
    dns_provider: str | None = None
    # Zones that the DNS provider and its token serve; only previews below them share a wildcard.
    dns_zones: list[str] = field(default_factory=list)
    # KEY=VALUE lines that become the Caddy service environment.
    env_file: Path | None = None

    def __post_init__(self) -> None:
        # These values go into Caddy config lines; a newline would inject more config.
        if self.acme_email is not None and (_has_whitespace(self.acme_email) or "@" not in self.acme_email):
            msg = f"--acme-email must be one address with no spaces: {self.acme_email!r}"
            raise KitshnError(msg)
        if self.dns_provider is not None and (not self.dns_provider.strip() or "\n" in self.dns_provider or "\r" in self.dns_provider):
            msg = "--dns-provider must be one non-empty line"
            raise KitshnError(msg)
        for zone in self.dns_zones:
            if zone != zone.lower() or zone.endswith(".") or "." not in zone or "*" in zone or _has_whitespace(zone):
                msg = f"--dns-zone must be a lowercase domain without a trailing dot, such as example.com: {zone!r}"
                raise KitshnError(msg)
        if self.dns_zones and not self.dns_provider:
            msg = "--dns-zone needs --dns-provider"
            raise KitshnError(msg)

    @property
    def empty(self) -> bool:
        return not self.modules and not self.acme_email and not self.dns_provider and self.env_file is None


@dataclass(frozen=True, slots=True)
class HostCheck:
    name: str
    state: Literal["ok", "warn", "fail"]
    detail: str


def configure_caddy_host(
    settings: CaddyHostSettings,
    runner: CommandRunner,
    *,
    lock: Callable[[], AbstractContextManager[object]] = nullcontext,
) -> bool:
    """Bring the host Caddy to `settings`. Returns True when it changed anything.

    A new binary or a new service environment needs a restart, because a reload keeps the
    running process. A restart drops open connections for about a second. Options alone reload.
    Any failure restores every file and the binary. A module build runs before `lock`, so a
    long build does not hold deploys; the changes to the live Caddy run inside it.
    """

    if settings.empty:
        return False
    if settings.dns_provider and not settings.dns_zones:
        print("warning: --dns-provider without --dns-zone adds no wildcard preview sites", file=sys.stderr)
    if runner.dry_run:
        # The checks below read real binaries and files; a dry run only names the step.
        print(f"+ configure host Caddy: {settings}")
        return False

    with tempfile.TemporaryDirectory(prefix="kitshn-caddy-") as out:
        built = _build_if_needed(settings.modules, runner, Path(out))
        with lock():
            return _apply(settings, built, runner)


def caddy_host_checks(runner: CommandRunner) -> list[HostCheck]:
    """Doctor checks for the opt-in host setup. Empty when the host does not use it."""

    checks: list[HostCheck] = []
    if PACKAGED_BINARY.exists() and CADDY_BINARY.exists():
        packaged = _caddy_version_or_none(runner, PACKAGED_BINARY)
        running = _caddy_version_or_none(runner, CADDY_BINARY)
        if packaged is not None and packaged == running:
            checks.append(HostCheck("caddy build version", "ok", packaged))
        else:
            checks.append(
                HostCheck(
                    "caddy build version",
                    "warn",
                    f"package {packaged}, custom build {running}; rerun bootstrap with --caddy-module",
                )
            )
    if caddy_dns_zones() or _options_have_dns():
        checks.append(_env_file_check())
    return checks


def with_options_import(content: str) -> str:
    """`content` with `import <options file>` inside its global options block, added when missing."""

    import_line = f"import {CADDY_OPTIONS_FILE}"
    lines = content.splitlines()
    if any(line.strip() == import_line for line in lines):
        return content
    for index, line in enumerate(lines):
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped == "{":
            lines.insert(index + 1, f"\t{import_line}")
            return "\n".join(lines) + "\n"
        break
    return "\n".join(["{", f"\t{import_line}", "}", "", *lines]) + "\n"


def _apply(settings: CaddyHostSettings, built: Path | None, runner: CommandRunner) -> bool:
    snapshot = _Snapshot.take([CADDY_ENV_FILE, SYSTEMD_DROP_IN, CADDY_OPTIONS_FILE, CADDY_BASE_CONFIG])
    binary_changed = False
    diverted_now = False
    caddy_touched = False
    try:
        if built is not None:
            # Set first: a half-done install must restore too.
            binary_changed = True
            diverted_now = _install(runner, built)
        env_changed = False
        drop_in_changed = False
        if settings.env_file is not None:
            env = _caddy_env(settings.env_file)
            # Only root and the Caddy service user read the token; validation runs as that user.
            group = caddy_group(runner)
            mode = 0o600 if group is None else 0o640
            env_changed = _write_if_changed(CADDY_ENV_FILE, env, group=group, mode=mode)
            drop_in_changed = _write_if_changed(SYSTEMD_DROP_IN, _drop_in())
        options_changed = False
        if settings.acme_email or settings.dns_provider:
            if settings.dns_provider and not _env_file_has_values():
                # A `dns` option without its token fails the whole TLS app: every site goes down.
                msg = "--dns-provider needs the token in Caddy's environment: pass --caddy-env-file"
                raise KitshnError(msg)
            options = _options(settings.acme_email, settings.dns_provider, settings.dns_zones)
            options_changed = _write_if_changed(CADDY_OPTIONS_FILE, options)
            base = CADDY_BASE_CONFIG.read_text(encoding="utf-8") if CADDY_BASE_CONFIG.exists() else ""
            options_changed |= _write_if_changed(CADDY_BASE_CONFIG, with_options_import(base))
        if not (binary_changed or env_changed or drop_in_changed or options_changed):
            return False

        validate = runner.run(caddy_validate_command(runner), capture=True, check=False)
        if validate.returncode != 0:
            detail = redact_caddy_env(validate.stderr.strip() or validate.stdout.strip())
            msg = f"the new Caddy host setup fails validation, restored the previous one: {detail}"
            raise KitshnError(msg)

        caddy_touched = True
        if drop_in_changed:
            runner.run(["systemctl", "daemon-reload"])
        if binary_changed or env_changed or drop_in_changed:
            runner.run(["systemctl", "restart", "caddy"])
        else:
            runner.run(["caddy", "reload", "--config", str(CADDY_BASE_CONFIG)])
    except Exception:
        snapshot.restore()
        if binary_changed:
            _restore_binary(runner, diverted_now=diverted_now)
        runner.run(["systemctl", "daemon-reload"], check=False)
        if caddy_touched:
            # The running Caddy took the new setup or died with it; start it on the restored one.
            runner.run(["systemctl", "restart", "caddy"], check=False)
        raise
    PREVIOUS_BINARY.unlink(missing_ok=True)
    return True


def _restore_binary(runner: CommandRunner, *, diverted_now: bool) -> None:
    if diverted_now:
        # This run added the diversion: drop it, and dpkg moves the packaged binary back.
        runner.run(["rm", "-f", str(CADDY_BINARY)], check=False)
        runner.run(["dpkg-divert", "--local", "--rename", "--remove", str(CADDY_BINARY)], check=False)
    elif PREVIOUS_BINARY.exists():
        runner.run(["install", "-m", "0755", str(PREVIOUS_BINARY), str(CADDY_BINARY)], check=False)
    runner.run(["rm", "-f", str(PREVIOUS_BINARY)], check=False)


def _options(acme_email: str | None, dns_provider: str | None, dns_zones: list[str]) -> str:
    lines = [GENERATED_HEADER]
    if acme_email:
        # Explicit issuers, so that sites with their own `tls { dns }` also fall back to ZeroSSL.
        lines.extend(
            [
                f"email {acme_email}",
                "cert_issuer acme",
                "cert_issuer acme {",
                f"\tdir {ZEROSSL_ACME_DIRECTORY}",
                "}",
            ]
        )
    if dns_provider:
        lines.extend(f"{DNS_ZONE_MARKER}{zone}" for zone in sorted(dns_zones))
        lines.append(f"dns {dns_provider}")
    return "\n".join(lines) + "\n"


def _drop_in() -> str:
    # EnvironmentFile: systemd reads the file as root. A missing file stops the start with
    # "Failed to load environment files" and prints no value. Without `--environ`: the stock
    # unit prints the whole environment, a token too, to the journal.
    return "\n".join(
        [
            GENERATED_HEADER,
            "[Service]",
            f"EnvironmentFile={CADDY_ENV_FILE}",
            "ExecStart=",
            f"ExecStart={CADDY_BINARY} run --config {CADDY_BASE_CONFIG}",
            "",
        ]
    )


def _caddy_env(source: Path) -> str:
    values = read_env_file(source)
    if not values:
        msg = f"the Caddy environment file has no values: {source}"
        raise KitshnError(msg)
    for key, value in values.items():
        if not value or any(char.isspace() or char in "\"'#\\" for char in value):
            msg = f"the Caddy environment value {key} is empty or has spaces, quotes, '#', or '\\'"
            raise KitshnError(msg)
    return GENERATED_HEADER + "\n" + "".join(f"{key}={values[key]}\n" for key in sorted(values))


def _env_file_has_values() -> bool:
    try:
        values = read_env_file(CADDY_ENV_FILE)
    except (KitshnError, OSError):
        return False
    return bool(values) and all(values.values())


def _options_have_dns() -> bool:
    if not CADDY_OPTIONS_FILE.exists():
        return False
    lines = CADDY_OPTIONS_FILE.read_text(encoding="utf-8").splitlines()
    return any(line.strip().startswith("dns ") for line in lines)


def _env_file_check() -> HostCheck:
    name = "caddy dns token"
    if not CADDY_ENV_FILE.exists():
        return HostCheck(name, "fail", f"missing {CADDY_ENV_FILE}; the global dns option needs it")
    info = CADDY_ENV_FILE.stat()
    if info.st_uid != 0 or info.st_mode & stat.S_IRWXO or info.st_mode & (stat.S_IWGRP | stat.S_IXGRP):
        return HostCheck(name, "fail", f"{CADDY_ENV_FILE} must be root-owned, mode 0640 or 0600")
    if not _env_file_has_values():
        return HostCheck(name, "fail", f"{CADDY_ENV_FILE} has no values or an empty value")
    if not SYSTEMD_DROP_IN.exists():
        return HostCheck(name, "fail", f"missing {SYSTEMD_DROP_IN}; Caddy does not load the token")
    return HostCheck(name, "ok", str(CADDY_ENV_FILE))


def _write_if_changed(path: Path, content: str, *, group: int | None = None, mode: int = 0o644) -> bool:
    """Write `content` via rename when it differs, as root:`group` with `mode`. True when it wrote."""

    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    handle, temp_name = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name}.")
    with os.fdopen(handle, "w", encoding="utf-8") as temp:
        temp.write(content)
    temp_path = Path(temp_name)
    if group is not None:
        os.chown(temp_path, 0, group)
    temp_path.chmod(mode)
    os.replace(temp_path, path)
    return True


@dataclass(frozen=True, slots=True)
class _Snapshot:
    files: dict[Path, bytes | None]

    @classmethod
    def take(cls, paths: list[Path]) -> _Snapshot:
        return cls({path: path.read_bytes() if path.exists() else None for path in paths})

    def restore(self) -> None:
        for path, content in self.files.items():
            if content is None:
                path.unlink(missing_ok=True)
            else:
                path.write_bytes(content)


def _build_if_needed(modules: list[CaddyModule], runner: CommandRunner, out: Path) -> Path | None:
    """Build the packaged Caddy version plus `modules` into `out`, unless /usr/bin/caddy is one.

    The target is the packaged version: /usr/bin/caddy.default after the diversion, else
    /usr/bin/caddy. After `apt-get upgrade caddy`, the next run builds the new version.
    """

    if not modules:
        return None
    target_version = _caddy_version(runner, PACKAGED_BINARY if PACKAGED_BINARY.exists() else CADDY_BINARY)
    if _has_build(runner, CADDY_BINARY, target_version, modules):
        return None
    if not runner.exists("dpkg-divert"):
        # Limit: only dpkg hosts (Debian, Ubuntu) keep a custom build safe from package upgrades.
        # Revisit when a KitSHn host on another distro needs a Caddy module.
        msg = "installing Caddy modules needs dpkg-divert (Debian or Ubuntu hosts)"
        raise KitshnError(msg)
    built = out / "caddy"
    _build(runner, target_version, modules, out)
    if not _has_build(runner, built, target_version, modules):
        msg = f"the new Caddy build does not report {target_version} with {', '.join(map(str, modules))}"
        raise KitshnError(msg)
    return built


def _caddy_version(runner: CommandRunner, binary: Path) -> str:
    version = _caddy_version_or_none(runner, binary)
    if version is None:
        msg = f"cannot read the Caddy version from {binary}"
        raise KitshnError(msg)
    return version


def _caddy_version_or_none(runner: CommandRunner, binary: Path) -> str | None:
    result = runner.run([str(binary), "version"], capture=True, check=False)
    version = result.stdout.split(maxsplit=1)[0] if result.stdout.strip() else ""
    return version if result.returncode == 0 and version.startswith("v2.") else None


def _has_build(runner: CommandRunner, binary: Path, version: str, modules: list[CaddyModule]) -> bool:
    if not binary.exists():
        return False
    if _caddy_version_or_none(runner, binary) != version:
        return False
    info = runner.run([str(binary), "build-info"], capture=True).stdout
    deps = {
        (fields[1], fields[2])
        for line in info.splitlines()
        if len(fields := line.split("\t")) >= 3 and fields[0] == "dep"
    }
    return all((module.path, module.version) in deps for module in modules)


def _build(runner: CommandRunner, version: str, modules: list[CaddyModule], out: Path) -> None:
    with_args = [arg for module in modules for arg in ("--with", str(module))]
    runner.run(
        [
            "docker",
            "run",
            "--rm",
            # The build shares the host with live sites; leave CPU for them.
            "--cpus",
            "2",
            "--env",
            "CGO_ENABLED=0",
            "--volume",
            f"{out}:/out",
            f"caddy:{version.removeprefix('v')}-builder",
            "xcaddy",
            "build",
            version,
            *with_args,
            "--output",
            "/out/caddy",
        ]
    )


def _install(runner: CommandRunner, built: Path) -> bool:
    """Install `built` as /usr/bin/caddy. True when this call added the dpkg diversion."""

    runner.run(["cp", "--preserve=mode", str(CADDY_BINARY), str(PREVIOUS_BINARY)])
    diversion = runner.run(["dpkg-divert", "--list", str(CADDY_BINARY)], capture=True).stdout
    diverted_now = str(PACKAGED_BINARY) not in diversion
    if diverted_now:
        runner.run(
            [
                "dpkg-divert",
                "--local",
                "--rename",
                "--divert",
                str(PACKAGED_BINARY),
                "--add",
                str(CADDY_BINARY),
            ]
        )
    runner.run(["install", "-m", "0755", str(built), str(CADDY_BINARY)])
    return diverted_now


def _has_whitespace(value: str) -> bool:
    return any(char.isspace() for char in value)
